# Generated by Django 2.2.9 on 2020-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helevents', '0004_auto_20180109_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
