# Generated by Django 2.2.9 on 2020-02-07 13:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_add_tavastiaevents_fields_to_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
