# Generated by Django 2.2.9 on 2020-02-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0075_change_place_srid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='license',
            field=models.ForeignKey(default='event_only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='events.License', verbose_name='License'),
        ),
    ]
