version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      docker: 18
  build:
    commands:
      - mv local_settings.py.prod local_settings.py
      - ./install_gdal_ubuntu.sh
      - INSTALL_BASE=$CODEBUILD_SRC_DIR
      - virtualenv -p python3 $INSTALL_BASE/venv
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $REGISTRY_ID.dkr.ecr.eu-west-1.amazonaws.com
      - pip install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}')
      - pip install -r requirements.txt
      - mv local_settings.py local_settings.py.prod
      - python manage.py install_templates tavastiaevents
      - mv local_settings.py.prod local_settings.py
      - docker build -f docker/django/Dockerfile --target production -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:latest
      - aws ecs update-service --cluster hameevents-api --service $IMAGE_NAME --force-new-deployment --region eu-west-1
      - mv local_settings.py local_settings.py.prod
      - python manage.py collectstatic
      - aws s3 sync --cache-control 'public, max-age=3600' --no-progress static/ s3://hame-events-client/$STAGE/static/